services:
  grafana:
    image: grafana/grafana:11.3.0
    container_name: epimetheus-grafana
    restart: unless-stopped

    ports:
      - "3000:3000"

    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Editor"
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "epimetheus"
      GF_ANALYTICS_REPORTING_ENABLED: "false"
      GF_ANALYTICS_CHECK_FOR_UPDATES: "false"
      GF_NEWS_NEWS_FEED_ENABLED: "false"

    volumes:
      - grafana-data:/var/lib/grafana

    extra_hosts:
      - "host.docker.internal:host-gateway"

    mem_limit: 512m

volumes:
  grafana-data:
